### ISSUE TITLE
Destroy resource

### ISSUE THREAD

**Issue by Sanes** [hotwired-laravel/turbo-laravel#100] opened 2023-02-16 03:08 UTC
Hello!
CommentController
```
    public function destroy(Comment $comment)
    {
        $comment->delete();
        return turbo_stream()->remove($comment);
    }
```
Return to download file 18
```
<turbo-stream target="comment_18" action="remove">
</turbo-stream>
```

**Comment by tonysm** [comment] 2023-02-16 15:57
Hey @Sanes 

That looks like the expected behavior. What's the issue here?

I'm going to close the issue, but feel free to reopen it if you think something is not working as it should (with more context).

**Closed by tonysm** 2023-02-16 15:57 UTC

**Comment by Sanes** [comment] 2023-02-17 07:04
I can't figure out how to implement resource deletion. In my example, it is suggested to download a file.
